[package]
name = "jan-furry-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_asset_loader = "0.20.0"
bevy_render = "0.13.2"
image = "0.25.1"
winit = "0.29.15"

[lints.clippy]
nursery = "deny"
pendantic = "deny"